# version: '3'
services:
  backend:
    container_name: backend
    # image: georgekibe/django_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - static:/static
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - selenium
    networks:
      - realestatenetwork
    restart: always
  
  frontend:
    container_name: frontend
    # image: georgekibe/next_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    networks:
      - realestatenetwork
    depends_on:
      - backend
    restart: always

  selenium:
    environment:
      - VNC_NO_PASSWORD=1
    image: selenium/standalone-chrome:117.0
    ports:
      - 7900:7900
    networks:
      - realestatenetwork
    restart: always
  
  nginx: 
    build: ./backend/nginx
    volumes:
     - static:/static
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - realestatenetwork
    restart: always

volumes:
  static:
  
networks:
  realestatenetwork:
    driver: bridge