# Generated by Django 5.0.6 on 2024-07-04 06:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university_name", models.CharField(max_length=255, null=True)),
                ("start_date", models.CharField(max_length=100, null=True)),
                ("end_date", models.CharField(max_length=100, null=True)),
                ("degree", models.CharField(max_length=100, null=True)),
                ("major", models.CharField(max_length=100, null=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("company_name", models.CharField(max_length=255, null=True)),
                ("city", models.CharField(max_length=100, null=True)),
                ("state", models.CharField(max_length=100, null=True)),
                ("start_date", models.CharField(max_length=100, null=True)),
                ("end_date", models.CharField(blank=True, max_length=100, null=True)),
                ("currently_working", models.BooleanField(default=False)),
                ("work_summary", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "resumeId",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=100)),
                ("userName", models.CharField(max_length=100)),
                ("userEmail", models.CharField(max_length=100)),
                ("firstName", models.CharField(max_length=100, null=True)),
                ("lastName", models.CharField(max_length=100, null=True)),
                ("jobTitle", models.CharField(max_length=255, null=True)),
                ("address", models.CharField(max_length=100, null=True)),
                ("themeColor", models.CharField(max_length=7, null=True)),
                ("phone", models.CharField(max_length=100, null=True)),
                ("summary", models.TextField(null=True)),
                ("skills", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "education",
                    models.ManyToManyField(
                        null=True, related_name="resumes", to="resume.education"
                    ),
                ),
                (
                    "experience",
                    models.ManyToManyField(
                        null=True, related_name="resumes", to="resume.experience"
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume",
                "verbose_name_plural": "Resumes",
            },
        ),
    ]
