# Generated by Django 5.0.6 on 2024-07-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="firstName",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="lastName",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="phone",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="skills",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="summary",
            field=models.TextField(null=True),
        ),
    ]
