# Generated by Django 5.0.6 on 2024-07-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0002_resume_address_resume_firstname_resume_lastname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university_name", models.CharField(max_length=255, null=True)),
                ("start_date", models.CharField(max_length=100, null=True)),
                ("end_date", models.CharField(max_length=100, null=True)),
                ("degree", models.CharField(max_length=100, null=True)),
                ("major", models.CharField(max_length=100, null=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("company_name", models.CharField(max_length=255, null=True)),
                ("city", models.CharField(max_length=100, null=True)),
                ("state", models.CharField(max_length=100, null=True)),
                ("start_date", models.CharField(max_length=100, null=True)),
                ("end_date", models.CharField(blank=True, max_length=100, null=True)),
                ("currently_working", models.BooleanField(default=False)),
                ("work_summary", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("rating", models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="resume",
            name="job_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="theme_color",
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.RemoveField(
            model_name="resume",
            name="skills",
        ),
        migrations.AddField(
            model_name="resume",
            name="education",
            field=models.ManyToManyField(
                related_name="profiles", to="resume.education"
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="experience",
            field=models.ManyToManyField(
                related_name="profiles", to="resume.experience"
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="skills",
            field=models.ManyToManyField(related_name="profiles", to="resume.skill"),
        ),
    ]
