# Generated by Django 5.0.6 on 2024-07-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0003_education_experience_skill_resume_job_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="education",
            field=models.ManyToManyField(
                null=True, related_name="resumes", to="resume.education"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="experience",
            field=models.ManyToManyField(
                null=True, related_name="resumes", to="resume.experience"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="skills",
            field=models.ManyToManyField(
                null=True, related_name="resumes", to="resume.skill"
            ),
        ),
    ]
