# Generated by Django 5.0.6 on 2024-07-02 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0004_alter_resume_education_alter_resume_experience_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="job_title",
            new_name="jobTitle",
        ),
        migrations.RenameField(
            model_name="resume",
            old_name="theme_color",
            new_name="themeColor",
        ),
    ]
