# Generated by Django 5.0.6 on 2024-07-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0005_rename_job_title_resume_jobtitle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="skills",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.AddField(
            model_name="resume",
            name="skills",
            field=models.JSONField(null=True),
        ),
    ]
