# Generated by Django 5.0.6 on 2024-07-04 06:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("house_type", models.CharField(blank=True, max_length=50)),
                ("additional_info", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="Property Title"),
                ),
                (
                    "link",
                    models.CharField(max_length=250, verbose_name="Property Link"),
                ),
                (
                    "description",
                    models.TextField(
                        default="Default description...update me please....",
                        verbose_name="Description",
                    ),
                ),
                (
                    "property_detail_link",
                    models.CharField(
                        default="", max_length=500, verbose_name="Property detail Link"
                    ),
                ),
                (
                    "city",
                    models.CharField(default="", max_length=180, verbose_name="City"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        default="140",
                        max_length=100,
                        null=True,
                        verbose_name="Postal Code",
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        default="", max_length=150, verbose_name="Street Address"
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        default="", max_length=150, verbose_name="Price Range"
                    ),
                ),
                (
                    "email_listing",
                    models.CharField(
                        default="", max_length=500, verbose_name="Listing Email"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        default="", max_length=50, verbose_name="Phone Number"
                    ),
                ),
                (
                    "details_link",
                    models.CharField(
                        default="", max_length=50, verbose_name="Details Link"
                    ),
                ),
                (
                    "application_link",
                    models.CharField(
                        default="", max_length=100, verbose_name="Application Email"
                    ),
                ),
                (
                    "plot_area",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="Plot Area(m^2)",
                    ),
                ),
                (
                    "total_floors",
                    models.IntegerField(default=0, verbose_name="Number of floors"),
                ),
                ("bedrooms", models.IntegerField(default=1, verbose_name="Bedrooms")),
                (
                    "bathrooms",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=4,
                        verbose_name="Bathrooms",
                    ),
                ),
                (
                    "advert_type",
                    models.CharField(
                        default="FOR RENT", max_length=50, verbose_name="Advert Type"
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        default="Apartment", max_length=50, verbose_name="Property Type"
                    ),
                ),
                ("images", models.JSONField(blank=True, default=list, null=True)),
                ("amenities", models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
        ),
    ]
