# Generated by Django 5.0.6 on 2024-06-07 08:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="Property Title"),
                ),
                ("link", models.UUIDField()),
                (
                    "description",
                    models.TextField(
                        default="Default description...update me please....",
                        verbose_name="Description",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Nairobi", max_length=180, verbose_name="City"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        default="140", max_length=100, verbose_name="Postal Code"
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        default="MoiKG8 Avenue",
                        max_length=150,
                        verbose_name="Street Address",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="Price",
                    ),
                ),
                (
                    "plot_area",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="Plot Area(m^2)",
                    ),
                ),
                (
                    "total_floors",
                    models.IntegerField(default=0, verbose_name="Number of floors"),
                ),
                ("bedrooms", models.IntegerField(default=1, verbose_name="Bedrooms")),
                (
                    "bathrooms",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=4,
                        verbose_name="Bathrooms",
                    ),
                ),
                (
                    "advert_type",
                    models.CharField(
                        default="FOR RENT", max_length=50, verbose_name="Advert Type"
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        default="Apartment", max_length=50, verbose_name="Property Type"
                    ),
                ),
                ("images", models.JSONField(default=list)),
                (
                    "published_status",
                    models.BooleanField(default=False, verbose_name="Published Status"),
                ),
                ("views", models.IntegerField(default=0, verbose_name="Total Views")),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
        ),
    ]
