# Generated by Django 5.0.6 on 2024-06-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_property_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="published_status",
        ),
        migrations.RemoveField(
            model_name="property",
            name="views",
        ),
        migrations.AlterField(
            model_name="property",
            name="images",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
