# Generated by Django 5.0.6 on 2024-06-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_property_application_link_property_details_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.CharField(
                default="", max_length=150, verbose_name="Price Range"
            ),
        ),
    ]
