# Generated by Django 5.0.6 on 2024-06-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_property_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="postal_code",
            field=models.CharField(
                default="140", max_length=100, null=True, verbose_name="Postal Code"
            ),
        ),
    ]
