# Generated by Django 5.0.6 on 2024-06-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_property_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="amenities",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
